#!/bin/sh

set -e

yaourt -Syua --noconfirm

sudo pacman -S --noconfirm \
  xorg-server xorg-xinit \
  gtk-engine-murrine \
  imagemagick feh python-setuptools \
  xorg-xrandr wmctrl xdotool dash alsa-utils \
  rofi \
  rxvt-unicode \
  firefox firefox-i18n-ja \
  vim

yaourt -S --noconfirm\
  python-pywal \
  openbox-patched \
  lemonbar \
  phallus-fonts-git siji-git

mkdir -p "${HOME}/.themes"
git clone --depth 1 https://github.com/dylanaraps/Flatabulous-wal.git "${HOME}/.themes/Flatabulous-wal"

mkdir -p "${HOME}/Pictures/Wallpapers"
curl -o "${HOME}/Pictures/Wallpapers/graffiti.jpg" https://wallpaperscraft.com/image/graffiti_wall_city_colorful_62146_3840x2160.jpg 

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

wal -i "${HOME}/Pictures/Wallpapers"
