#!/bin/sh

set -e

yaourt -Syua

sudo pacman -S --noconfirm \
  xorg-server xorg-xinit \
  openbox gtk-engine-murrine \
  imagemagick feh \
  xorg-xrandr wmctrl xdotool \
  rxvt-unicode \
  firefox firefox-i18n-ja \
  vim

yaourt -S \
  python-pywal \
  openbox-patched \
  lemonbar \
  phallus-fonts-git siji-git

mkdir -p "${HOME}/.themes"
git clone --depth 1 https://github.com/dylanaraps/Flatabulous-wal.git "${HOME}/.themes/Flatabulous-wal"

mkdir -p "${HOME}/.wallpaper"
curl -o "${HOME}/.wallpaper/graffiti.jpg" https://wallpaperscraft.com/image/graffiti_wall_city_colorful_62146_3840x2160.jpg 

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

wal -i "${HOME}/.wallpaper"
