#!/bin/sh

set -e

yaourt -Syua

sudo pacman -S --noconfirm \
  xor-server xorg-xinit \
  openbox gtk-engine-murrine \
  imagemagick feh \
  xorg-randr wmctrl xdotool \
  rxvt-unicode \
  firefox firefox-i18n-ja \
  vim

yaourt -S \
  openbox-patched \
  lemonbar phallus-fonts-git siji-git

mkdir -p "${HOME}/.theme"
git clone --depth 1 https://github.com/dylanaraps/Flatabulous-wal.git "${HOME}/.theme/Flatabulous-wal"

mkdir -p "${HOME}/.wallpaper"
wget https://wallpaperscraft.com/image/graffiti_wall_city_colorful_62146_3840x2160.jpg -O "${HOME}/.wallpaper/graffiti.jpg"

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

